### ISSUE TITLE
Generate an HTML file from result

### ISSUE THREAD

**Issue by lewispham** [aMarCruz/rollup-plugin-pug#12]
`rollup-plugin-postcss` has an option for extracting the result into a CSS file by specifying `extract: true`.

Does `rollup-plugin-pug` has a similar option like the above? Because it'll be super helpful for bundling html files.

**Comment by aMarCruz** [comment]
...mmm no @lewispham, sorry. Currently, it is a wrapper for the corresponding functions in the Pug API. The only special processing is for `import` directives, content manipulation is beyond the scope of this plugin.

In any case, PRs are welcome. Closing this issue now.
