### ISSUE TITLE
Upgrade rollup version

### ISSUE THREAD

**Issue by lewispham** [aMarCruz/rollup-plugin-pug#13]
`rollup-plugin-pug` currently only supports rollup v0.4.3. The recent rollup release actually changed the options `entry` and `src` to `input` and `output`. This is causing failed test cases if we run `rollup-plugin-pug` with latest rollup version (v0.6.5). `entry` and `src` will also be deprecated soon.

**Comment by aMarCruz** [comment]
@lewispham thanks. I will upgrade this library in a few days.

**Comment by aMarCruz** [comment]
@lewispham , done in v1.0.0

**Comment by lewispham** [comment]
Nice works. Thanks @aMarCruz .
