### ISSUE TITLE
plugin does not pass options as locals, but Pug itself does

### ISSUE THREAD

**Issue by StreetStrider** [aMarCruz/rollup-plugin-pug#5]
Hello.
I got pretty simple config I'm using for pug templates:
```js
{
	pretty: false,
	dev: false, // true or false
	basedir: 'path/here',
}
```
Pug pass `dev` property to all templates as local (and other two options as well). I expect `rollup-plugin-pug` to mimic this behavior when passing options to it. This isn't working as I expected, so if I would depend on `dev` in my templates I will got different rendering of template when using it directly via Pug renderer or via rollup plugin.

**Comment by aMarCruz** [comment]
Hi @StreetStrider , when you say "Pug" do you mean the command line? or some method of the API.

The `locals` was used by compatibility with an old Jade plugin.
I can see problems passing the same value through locals:

```js
{
	pretty: false,
	locals: { dev: false }, // true or false
	basedir: 'path/here',
}
```

This plugin does "static compilation" using the pug `compile` method and evaluating it immediately with the `locals` property of the options passed to the plugin.

I don't know if its a good idea mixing compiler options with the template's context values, anyway I'm releasing a new version for you with an undocumented `_pug_options` property in the scope, I can't change this behavior in current (minor) versions.

Closing this issue now.

**Comment by StreetStrider** [comment]
Ugh, I think I did a mistake here. I'm using Pug programmatical API to statically compile templates. I was obscured by Pug documentation for `render` which says that **«An options object, also used as the locals object.»**. So I believe that `pug.compile` share this behavior: i.e.
`pug.render(template, options_and_locals)` is equivalent to `pug.compile(template, options)(locals)` where `actual locals = Object.assign({}, options, locals)` for each invocation.

But this example proves that I was wrong and no actual «inheritance of locals» happens:
```js
var pug = require('pug')

var template =
`
div #{pretty}
div #{basedir}
div #{x}
div #{y}
div #{dev}
`

var options =
{
	pretty: true,
	basedir: '/tmp',
	x: 'x',
	y: 'y',
	dev: true
}

var r1 = pug.render(template, options)

console.log(r1)

var compiled = pug.compile(template, options)

var r2 = compiled({ y: 'y2' })

// here all except `y` would be empty
console.log(r2)
```

Looks like I should use `.static` feature of `rollup-plugin-pug` and if it uses `pug.render` under the hood, everything would work for me. Unless I should use `_pug_options` or use `locals`.

**Comment by StreetStrider** [comment]
@aMarCruz, hello. I'm sorry to bother you, but I think that when I use `.static` templates with this plugin, it should pass options as locals. I think so, because it is the behavior of Pug itself when you [`render` string directly](https://pugjs.org/api/reference.html#pugrendersource-options-callback).

There's obvious symmetry:
1. `pug.compile` ~ `import template.pug`
2. `pug.render` ~ `import template.static.pug`

However in (2) import does not works like `pug.render`. This might be because under the hood it is still a call to `pug.compile`, followed by immediate `template()` call (? I guess). I believe importing static template must mimic `pug.render`. Is this doable? `_pug_options` can be eliminated then. Thank you for any effort.

**Comment by aMarCruz** [comment]
@StreetStrider  this is:

`import template.static.pug` equivalent:
```js
  const converterFunction = pug.compile( template.static.pug, pug.options );
  const htmlString = converterFunction( locals );
  export default JSON.stringify( htmlString );
```

`import template.pug` :
```js
  const jsCode = pug.compileClientWithDependenciesTracked( template.pug, pug.options );
  // jsCode will be prefixed with the tracked dependencies and "export default"
  // ...to generate an ES6 JavaScript module
```

(where `pug.options` is a subset of options passed to rollup-plugin-pug).

Hope this help.

**Comment by StreetStrider** [comment]
@aMarCruz in case of static template why using `compileClientWithDependenciesTracked`? It's needed only if you need to track dependencies. When static template is processed, it is [instantly rendered to string](https://github.com/aMarCruz/rollup-plugin-pug/blob/0be5600db96eae4f24322d4396d329a2eabb02df/src/index.js#L96-L97). Why need to track dependencies for a generated string? Isn't it self-sufficient?

**Comment by StreetStrider** [comment]
Why're you using custom `assign`? If you're targeting modern environments, I believe, you're free to use `Object.assign` instead.

**Comment by aMarCruz** [comment]
@StreetStrider , the `import`s in my example were reversed, sorry! corrected now.

Custom `assign` is congruent with the transpiled code in dist/ (`Object.assign` is not ES5) ... and an old habit of mine.

**Comment by StreetStrider** [comment]
@aMarCruz 
> corrected now.

If you commit anything, please, can you push this to repo? I would like to see it. I'm planning to try to apply my idea with `render` and check if this would break any tests. I'm planning to eliminate previously introduced `_pug_options` as well.

**Comment by aMarCruz** [comment]
@StreetStrider only my comment was wrong, the code is corrent.
It is in [89-110](https://github.com/aMarCruz/rollup-plugin-pug/blob/master/src/index.js#L89-L110) of index.js
