### ISSUE TITLE
Keeping pug-runtime as external

### ISSUE THREAD

**Issue by QuentinRoy** [aMarCruz/rollup-plugin-pug#8]
Currently, whatever is registered in rollup.config.js, pug-runtime is embedded in the compiled file.
Is there any way not to bundle it with the library and keep it as an external?

**Comment by aMarCruz** [comment]
@QuentinRoy , not currently, sorry. I will add this feature in the next few days.

**Comment by aMarCruz** [comment]
@QuentinRoy , done in v0.1.5.

Please see the [Options](https://github.com/aMarCruz/rollup-plugin-pug#options) in the README for some examples.

**Comment by QuentinRoy** [comment]
@aMarCruz, thank you for your work!

However it seems the new version introduces a regression and I cannot install it. Please have a look at issue #9.
